import "./globals.css";
import type { Metadata } from "next";

import { Inter, Roboto_Mono } from "next/font/google";

import { AuthProvider } from "./_components/MentorUserProvider";
import SessionProvider from "../components/SessionProvider";
import { HomeChat } from "./_components/Chat";
import BottomNavigation from "../components/BottomNavigation";

const inter = Inter({
  variable: "--font-sans",
  subsets: ["latin"],
});

const robotoMono = Roboto_Mono({
  variable: "--font-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable} ${robotoMono.variable}`}>
      <body className="antialiased">
        <SessionProvider>
          <AuthProvider>
            <HomeChat />
            {children}
            <BottomNavigation />
          </AuthProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
