"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CalendarRouter = void 0;
const express_1 = require("express");
const token_checker_1 = require("../middleware/token-checker");
const mentor_calendar_1 = require("../controller/mentor-calendar");
const mentor_get_calendar_1 = require("../controller/mentor-get-calendar");
exports.CalendarRouter = (0, express_1.Router)();
exports.CalendarRouter.post("/Calendar", token_checker_1.MentorTokenChecker, mentor_calendar_1.UpdateMentorAvailability);
exports.CalendarRouter.get("/calendar/:mentorId", mentor_get_calendar_1.getMentorCalendar);
