"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CategoryRouter = void 0;
const express_1 = require("express");
const mentor_seed_categories_1 = require("../controller/mentor-seed-categories");
const mentor_get_categories_1 = require("../controller/mentor-get-categories");
const mentor_create_categories_1 = require("../controller/mentor-create-categories");
const mentor_add_sub_categories_1 = require("../controller/mentor-add-sub-categories");
exports.CategoryRouter = (0, express_1.Router)();
exports.CategoryRouter.post("/mentor-seed-category", mentor_seed_categories_1.seedCategories);
exports.CategoryRouter.get("/mentor-get-category", mentor_get_categories_1.getCategories);
exports.CategoryRouter.post("/mentor-creat-category", mentor_create_categories_1.createCategory);
exports.CategoryRouter.post("/mentor-sub-category/:categoryId", mentor_add_sub_categories_1.addSubCategories);
