"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.MentorRouter = void 0;
const express_1 = require("express");
const mentor_register_1 = require("../controller/mentor-register");
const mentor_login_1 = require("../controller/mentor-login");
const token_checker_1 = require("../middleware/token-checker");
const mentor_create_profile_1_1 = require("../controller/mentor-create-profile-1");
const mentor_forget_Password_1 = require("../controller/mentor-forget-Password");
const mentor_get_profile_1 = require("../controller/mentor-get-profile");
const mentor_find_forReset_1 = require("../controller/mentor-find-forReset");
const mentor_create_profile_2_1 = require("../controller/mentor-create-profile-2");
const mentor_create_profile_3_1 = require("../controller/mentor-create-profile-3");
const mentor_edit_profile_1 = require("../controller/mentor-edit-profile");
const mentor_verify_1 = require("../controller/mentor-verify");
const mentor_get_by_id_1 = require("../controller/mentor-get-by-id");
const mentor_get_all_1 = require("../controller/mentor-get-all");
exports.MentorRouter = (0, express_1.Router)();
exports.MentorRouter.post("/mentorEmail", mentor_register_1.MentorCheckemail);
exports.MentorRouter.post("/mentorOtp", mentor_register_1.checkOtp);
exports.MentorRouter.post("/mentorSignup", mentor_register_1.MentorSignUp);
exports.MentorRouter.post("/mentorProfile/step1", token_checker_1.MentorTokenChecker, mentor_create_profile_1_1.MentorCreateProfile1);
exports.MentorRouter.patch("/mentorProfile/step2", token_checker_1.MentorTokenChecker, mentor_create_profile_2_1.MentorCreateProfileStep2);
exports.MentorRouter.patch("/mentorProfile/step3", token_checker_1.MentorTokenChecker, mentor_create_profile_3_1.MentorCreateProfileStep3);
exports.MentorRouter.get("/mentorProfile", token_checker_1.MentorTokenChecker, mentor_get_profile_1.MentorGetProfile);
exports.MentorRouter.post("/mentorProfile/step1", token_checker_1.MentorTokenChecker, mentor_create_profile_1_1.MentorCreateProfile1);
exports.MentorRouter.patch("/mentorProfile/step2", token_checker_1.MentorTokenChecker, mentor_create_profile_2_1.MentorCreateProfileStep2);
exports.MentorRouter.patch("/mentorProfile/step3", token_checker_1.MentorTokenChecker, mentor_create_profile_3_1.MentorCreateProfileStep3);
exports.MentorRouter.get("/mentorProfile", token_checker_1.MentorTokenChecker, mentor_get_profile_1.MentorGetProfile);
exports.MentorRouter.post("/mentorLogin", mentor_login_1.MentorLogin);
exports.MentorRouter.put("/mentorResetPassword", mentor_forget_Password_1.mentorForgetPass);
exports.MentorRouter.post("/findMail", mentor_find_forReset_1.findmail);
exports.MentorRouter.put("/mentorEditProfile", token_checker_1.MentorTokenChecker, mentor_edit_profile_1.editMentorProfile);
exports.MentorRouter.post("/mentorVerify", mentor_verify_1.mentorVerify);
exports.MentorRouter.get("/mentor/:id", mentor_get_by_id_1.getMentorById);
exports.MentorRouter.get("/mentors", mentor_get_all_1.getAllMentors);
